version: '2'
services:
  bench:
    image: matsuu/isucon4-qualifier-bench:latest
    links:
      - nginx
      - mysql
  nginx:
    build: /Users/kojiMac/IdeaProjects/docker-isucon/isucon4-qualifier/nginx
    links:
      - webapp
    ports:
      - "80:80"
  webapp:
    #image: matsuu/isucon4-qualifier-webapp-go:latest
    build: /Users/kojiMac/IdeaProjects/docker-isucon/isucon4-qualifier/webapp/go
    links:
       - mysql
    ports:
      - "8080"
    environment:
      ISU4_DB_USER: isucon
      ISU4_DB_PASSWORD: isucon
      ISU4_DB_HOST: mysql
      ISU4_DB_PORT: 3306
  mysql:
    image: mysql:5.5
    ports:
      - "3306"
    command: ["--max_allowed_packet=300M"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
