version: '2'
services:
  bench:
    image: matsuu/isucon4-qualifier-bench:latest
    links:
      - nginx
      - mysql
  nginx:
    image: matsuu/isucon4-qualifier-nginx:latest
    links:
      - webapp
    ports:
      - "80:80"
  webapp:
    image: matsuu/isucon4-qualifier-webapp-ruby:latest
    links:
       - mysql
    ports:
      - "8080"
    environment:
      ISU4_DB_USER: isucon
      ISU4_DB_PASSWORD: isucon
      ISU4_DB_HOST: mysql
      ISU4_DB_PORT: 3306
  mysql:
    image: matsuu/isucon4-qualifier-mysql:latest
    ports:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
